config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  get 'users/new'

  root                 'static_pages#index'
  get     'help'    => 'static_pages#help'
  get     'about'   => 'static_pages#about'
  get     'contact' => 'static_pages#contact'
  get     'signup'  => 'users#new'
  get     'login'   => 'sessions#new'
  post    'login'   => 'sessions#create'
  delete  'logout'  => 'sessions#destroy'
  post    'create/newsletter' => 'application#create_newsletter'
  get 'set_language/english'
  get 'set_language/turkish'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations,  only: [:edit]
  resources :password_resets,      only: [:edit, :update, :create, :new]
  resources :microposts,           only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @micropost  = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def help
  end
  
  def about
  end
  
  def contact
  end

  def template1
      render 'templates/1/index', layout: false
  end

  def template2
      render 'templates/2/index', layout: false
  end

  def index
      @newsletter = Newsletter.new
      render 'index', layout: false
  end

  def template4
      render 'templates/4/index', layout: false
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
  The <a href="http://www.railstutorial.org/"><em>Ruby on Rails
  Tutorial</em></a> is a
  <a href="http://www.railstutorial.org/book">book</a> and
  <a href="http://screencasts.railstutorial.org/">screencast series</a>
  to teach web development with
  <a href="http://rubyonrails.org/">Ruby on Rails</a>.
  This is the sample application for the tutorial.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact</h1>
<p>
  Contact the Ruby on Rails Tutorial about the sample app at the
  <a href="http://www.railstutorial.org/#contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="http://www.railstutorial.org/#help">Rails Tutorial help
  section</a>.
  To get help on this sample app, see the
  <a href="http://www.railstutorial.org/book"><em>Ruby on Rails
  Tutorial</em> book</a>.
</p>

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="stats">
        <%= render 'shared/stats' %>
      </section>
      <section class="micropost_form">
        <%= render 'shared/micropost_form' %>
      </section>
    </aside>
    <div class="col-md-8">
      <h3>Micropost Feed</h3>
      <%= render 'shared/feed' %>
    </div>
  </div>
<% else %>
  <div class="center jumbotron">
    <h1>Welcome to the Sample App</h1>
  
    <h2>
      This is the home page for the
      <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
      sample application.
    </h2>
  
    <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
  </div>
<% end %>

app/views/static_pages/index.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="keywords" content="raporlama, teknoloji, veritabanı, görselleştirme, datlas, startup, data, veri"/>

    <meta name="description" content="Hızlı, Güvenilir, Kolay Raporlama.">
    <meta name="author" content="">

    <title><%= t('title') %></title>

    <!-- Bootstrap Core CSS -->
    <link href="templates/3/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Muli" rel="stylesheet">

    <!-- Plugin CSS -->
    <link rel="stylesheet" href="templates/3/vendor/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="templates/3/vendor/simple-line-icons/css/simple-line-icons.css">
    <link rel="stylesheet" href="templates/3/vendor/device-mockups/device-mockups.min.css">

    <!-- Theme CSS -->
    <link href="templates/3/css/new-age.min.css" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-87284969-1', 'auto');
      ga('send', 'pageview');
    </script>
</head>

<body id="page-top">

    <style type="text/css">
        body, p, h2, h3, h4, li, input {
            font-family: helvetica !important;
        }

        .email-input {
            width: inherit !important;
            display: initial;
            border: 2px solid #FDC842;
        }
        .btn-email-submit:hover {
            background-color: #B63059;
        }

        .btn-email-submit {
            background-color: #B63059;
        }
        @media screen and (min-width: 601px) {
            .contact-image {
                background-size: 100% 100% !important;
                
                padding:170px 0;
            }

            .bottom-form {
                text-align: left;
            }

            .langButton {
                margin-top: 17px;
                margin-left: 20px;
            }
        }

        @media screen and (max-width: 600px) {
            .contact-image {
                padding: 50px 0 !important;
                background-size: 100% 100% !important;
            }
            .bottom-form {
                margin-left: 0px !important;
            }
            .center-sm {
                text-align: center;
            }

            .langButton {
                float: left !important;
                margin-left: 15px;
            }
        }
    </style>
    <nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span> <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand page-scroll" href="#page-top">Datlas</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a class="page-scroll" href="#download"><%= t('about_us') %></a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#features"><%= t('features') %></a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#contact"><%= t('contact') %></a>
                    </li>
                    <% if session[:locale] == 'en' %>
                        <%= link_to set_language_turkish_path do %>
                            <li class="pull-right langButton"><span class="lang-sm" lang="tr"></span> TR</li>
                        <% end %>
                    <% else %>
                        <%= link_to set_language_english_path do %>
                            <li class="pull-right langButton"><span class="lang-sm" lang="en"></span><span class="langLabel"> EN</span></li>
                        <% end %>
                    <% end %>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>

    <header>
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <div class="header-content">
                        <div class="header-content-inner" style="position:relative;">
                            <h1>
                              <% if flash[:notice] %>
                                  <% flash.each do |name, msg| -%>
                                      <div style="color: #FDCB4E" id="flash">
                                        <%= content_tag :div, msg, class: 'text-center' %>
                                      </div>
                                  <% end -%>
                              <% end %>
                            </h1>
                            <h1 class="text-center" style="font-weight: bold;">DATLAS</h1>
                            <h2 class="text-center"><%= t('reporting_time') %></h2>
                            <h3 class="text-center"><%= t('general_features') %></h3>
                            <div class="text-center">
                                <a href="#download" class="btn btn-outline btn-xl page-scroll"><%= t('more') %></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <section id="download" class="download bg-primary text-center">
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-md-offset-2">
                    <h2 class="section-heading"><%= t('what_is') %></h2>
                    <h3><%= t('expl_1') %></h3>
                    <h3><%= t('expl_2') %></h3>
                    <h3><%= t('expl_3') %></h3>
                    <h4 style="color: white; margin-top: 100px;"><%= t('email_expl') %></h4>
                    <%= form_for @newsletter, url: create_newsletter_path, :html => {:multipart => true} do |f| %>
                        <div class="form col-md-offset-2 col-md-9 col-xs-12 text-center">
                          <%= f.email_field :email, class: 'form-control email-input', placeholder: '', required: true %>
                          <%= f.submit t('submit'), class: 'btn btn-outline btn-bg btn-email-submit' %>
                        </div>
                        <br/>
                    <% end %>
                    <h1>
                      <% if flash[:newsletter_alert] %>
                          <% flash.each do |name, msg| -%>
                              <div style="color: #FDCB4E" id="flash">
                                <%= content_tag :div, msg, class: 'text-center' %>
                              </div>
                          <% end -%>
                      <% end %>
                    </h1>
                </div>
            </div>
        </div>
    </section>

    <section id="features" class="features">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="section-heading">
                        <h2><%= t('feature_expl') %></h2>
                        <hr>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="feature-item">
                                    <i class="icon-hourglass text-primary"></i>
                                    <h3><%= t('fast') %></h3>
                                    <p class="text-muted"><%= t('fast_expl') %></p>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="feature-item">
                                    <i class="icon-shield text-primary"></i>
                                    <h3><%= t('secure') %></h3>
                                    <p class="text-muted"><%= t('secure_expl') %></p>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="feature-item">
                                    <i class="icon-magic-wand text-primary"></i>
                                    <h3><%= t('specialized') %></h3>
                                    <p class="text-muted"><%= t('specialized_expl') %></p>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="feature-item">
                                    <i class="icon-directions text-primary"></i>
                                    <h3><%= t('easy') %></h3>
                                    <p class="text-muted"><%= t('easy_expl') %></p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
    </section>

    <section id="contact" class="cta contact-image" style="background-image: url('templates/3/img/handshake2.jpg');">
        <div class="cta-content">
            <div class="container">
                <h2 class="center-sm" style="max-width:760px;"><%= t('dont_wait') %><br><%= t('meet_datlas') %></h2>
                <h4 class="center-sm" style="color: white"><%= t('email_expl') %></h4>
                <%= form_for @newsletter, url: create_newsletter_path, :html => {:multipart => true} do |f| %>
                    <div class="form col-md-6 col-xs-12 row text-center bottom-form">
                      <%= f.email_field :email, class: 'form-control email-input', placeholder: 'abc@def.com', required: true %>
                      <%= f.submit t('submit'), class: 'btn btn-outline btn-email-submit' %>
                    </div>
                    <br/>
                <% end %>
                <h1>
                  <% if flash[:newsletter_alert] %>
                      <% flash.each do |name, msg| -%>
                          <div style="color: #FDCB4E" id="flash">
                            <%= content_tag :div, msg, class: 'text-center' %>
                          </div>
                      <% end -%>
                  <% end %>
                </h1>
            </div>
        </div>
        <div class="overlay"></div>
    </section>

    <!-- jQuery -->
    <script src="templates/3/vendor/jquery/jquery.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="templates/3/vendor/bootstrap/js/bootstrap.min.js"></script>

    <!-- Plugin JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>

    <!-- Theme JavaScript -->
    <script src="templates/3/js/new-age.min.js"></script>

</body>

</html>